Fontname=''
Fontsize=''
PrimaryColour=''
Bold=''
Italic=''
Underline=''
StrikeOut=''
info=f'''
 [Script Info]
 ; Script generated by shaotao-art
 ; https://github.com/shaotao-art/pr_zimu
 Title: done.txt
 Original Script: None
 Script Updated By: version 2.8.01
 ScriptType: v4.00+
 Collisions: Normal
 PlayResY: 600
 PlayDepth: 0
 Timer: 100,0000
 Video Aspect Ratio: 0
 Video Zoom: 6
 Video Position: 0
  
 [V4+ Styles]
 Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
 Style: user_style, {Fontname}, {Fontsize}, & H{PrimaryColour}, & H00B4FCFC, & H00000008, & H80000008, {Bold}, {Italic}, {Underline}, {StrikeOut}, 100, 100, 0.00, 0.00, 1, 1.00, 2.00, 2, 30, 30, 30, 0
  
 [Events]
 Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
'''


Start=''
End=''
Text=''
each_dialogue=f'Dialogue: 0,{Start},{End},user_style, NTP,0000,0000,0000,,{Text}'

length=100
with open('done.ass','w',encoding='utf-8')as f:
    f.write(info)
    for i in range(0,length):
        f.write(each_dialogue)
